# Generated by Django 5.1.5 on 2025-04-05 15:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill", models.CharField(max_length=100)),
                ("years_of_experience", models.IntegerField()),
                ("description", models.TextField(default="", max_length=500)),
                ("image_link", models.URLField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="Profiency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(default="", max_length=50)),
                (
                    "skill_range",
                    models.SmallIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "about",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiency",
                        to="portfolio.about",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Profiency",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("linkedin", models.URLField(blank=True, default="")),
                ("github", models.URLField(blank=True, default="")),
                ("whatapp", models.URLField(blank=True, default="")),
                ("facebook", models.URLField(blank=True, default="")),
                ("twitter", models.URLField(blank=True, default="")),
                ("email", models.CharField(blank=True, default="", max_length=50)),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("display_pic", models.URLField(default="")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("WebDev", "WebDev"),
                            ("DataScience", "DataScience"),
                            ("AI", "AI"),
                            ("MachineLearning", "MachineLearning"),
                            ("ComputerVision", "ComputerVision"),
                            ("NLP", "NLP"),
                            ("Cybersecurity", "Cybersecurity"),
                            ("UIUX", "UIUX"),
                            ("ProductManagement", "ProductManagement"),
                            ("CloudComputing", "CloudComputing"),
                            ("Robotics", "Robotics"),
                            ("IoT", "IoT"),
                            ("BigData", "BigData"),
                            ("Blockchain", "Blockchain"),
                            ("MobileDev", "MobileDev"),
                            ("QA", "QA"),
                            ("SoftwareEng", "SoftwareEng"),
                            ("DataAnalysis", "DataAnalysis"),
                            ("DatabaseAdmin", "DatabaseAdmin"),
                            ("NetworkEng", "NetworkEng"),
                            ("Marketing", "Marketing"),
                            ("DigitalMarketing", "DigitalMarketing"),
                            ("SocialMedia", "SocialMedia"),
                            ("ContentMarketing", "ContentMarketing"),
                            ("Sales", "Sales"),
                            ("PublicRelations", "PublicRelations"),
                            ("Advertising", "Advertising"),
                            ("BrandManagement", "BrandManagement"),
                            ("ProductMarketing", "ProductMarketing"),
                            ("AgriMarketing", "AgriMarketing"),
                            ("HumanResources", "HumanResources"),
                            ("Finance", "Finance"),
                            ("Accounting", "Accounting"),
                            ("Banking", "Banking"),
                            ("InvestmentBanking", "InvestmentBanking"),
                            ("RealEstate", "RealEstate"),
                            ("Legal", "Legal"),
                            ("Education", "Education"),
                            ("Teaching", "Teaching"),
                            ("Research", "Research"),
                            ("Catering", "Catering"),
                            ("Hospitality", "Hospitality"),
                            ("EventManagement", "EventManagement"),
                            ("Fashion", "Fashion"),
                            ("Architecture", "Architecture"),
                            ("InteriorDesign", "InteriorDesign"),
                            ("Medical", "Medical"),
                            ("Pharmacy", "Pharmacy"),
                            ("Sports", "Sports"),
                            ("Entrepreneurship", "Entrepreneurship"),
                            ("Agriculture", "Agriculture"),
                            ("Others", "Others"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(default="", max_length=50)),
                ("thumbnail", models.URLField(default="")),
                ("project_link", models.URLField(default="")),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio",
                        to="portfolio.profile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="about",
            name="about",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="about",
                to="portfolio.profile",
            ),
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post", models.CharField(max_length=100)),
                ("start_year", models.DateField()),
                ("end_year", models.DateField()),
                ("company_name", models.CharField(default="", max_length=50)),
                (
                    "about",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume",
                        to="portfolio.about",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_year", models.DateField()),
                ("end_year", models.DateField()),
                ("school_name", models.CharField(default="", max_length=50)),
                (
                    "about",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school",
                        to="portfolio.about",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Schools",
            },
        ),
    ]
