# Generated by Django 5.1.5 on 2025-02-09 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="diplay_pic",
            new_name="display_pic",
        ),
        migrations.AlterField(
            model_name="about",
            name="_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="about",
                to="portfolio.profile",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="category",
            field=models.CharField(
                choices=[
                    ("FE", "Front End"),
                    ("BE", "Back End"),
                    ("DA", "Data Analyst"),
                    ("RB", "Robotics"),
                ],
                max_length=50,
            ),
        ),
    ]
