# Generated by Django 5.1.5 on 2026-07-28 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profiency',
            new_name='Proficiency',
        ),
        migrations.AlterModelOptions(
            name='proficiency',
            options={'verbose_name_plural': 'Proficiency'},
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proficiency', to='portfolio.about'),
        ),
    ]
