# Generated by Django 5.1.5 on 2025-02-09 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_rename_diplay_pic_profile_display_pic_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="about",
            old_name="_user",
            new_name="about",
        ),
    ]
