# Generated by Django 5.1.5 on 2025-02-09 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_rename__user_about_about"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="about",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="about",
                to="portfolio.profile",
            ),
        ),
    ]
