# Generated by Django 5.1.5 on 2025-02-10 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_alter_about_about"),
    ]

    operations = [
        migrations.RenameField(
            model_name="portfolio",
            old_name="_user",
            new_name="portfolio",
        ),
    ]
