# Generated by Django 5.1.5 on 2025-02-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_rename__user_portfolio_portfolio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="display_pic",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
    ]
