# Generated by Django 5.1.5 on 2025-02-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_alter_profile_display_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="display_pic",
            field=models.ImageField(upload_to="images"),
        ),
    ]
