# Generated by Django 5.1.5 on 2025-03-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_alter_profile_display_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="description",
            field=models.TextField(default="", max_length=500),
        ),
        migrations.AddField(
            model_name="about",
            name="image",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
        migrations.AddField(
            model_name="resume",
            name="company_name",
            field=models.CharField(default="", max_length=50),
        ),
    ]
