# Generated by Django 5.1.5 on 2025-03-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_about_description_about_image_resume_company_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="about",
            name="image",
        ),
        migrations.AddField(
            model_name="about",
            name="image_link",
            field=models.URLField(blank=True, default=""),
        ),
    ]
