# Generated by Django 5.1.5 on 2025-04-01 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_remove_about_image_about_image_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_year", models.DateField()),
                ("end_year", models.DateField()),
                ("school_name", models.CharField(default="", max_length=50)),
                (
                    "about",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school",
                        to="portfolio.about",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Schools",
            },
        ),
    ]
