# Generated by Django 5.1.5 on 2025-04-01 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_school"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="about",
            name="education",
        ),
        migrations.CreateModel(
            name="Profiency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(default="", max_length=50)),
                ("skill_range", models.CharField(default="", max_length=50)),
                (
                    "about",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiency",
                        to="portfolio.about",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Profiency",
            },
        ),
    ]
