# Generated by Django 5.1.5 on 2025-04-01 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_remove_about_education_profiency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profiency",
            name="skill_range",
            field=models.SmallIntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
