# Generated by Django 5.1.5 on 2025-04-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0012_alter_profiency_skill_range"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="project_link",
            field=models.URLField(default=""),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="thumbnail",
            field=models.URLField(default=""),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="category",
            field=models.CharField(
                choices=[
                    ("WD", "Web Development"),
                    ("DS", "Data Science"),
                    ("AI", "Artificial Intelligence"),
                    ("ML", "Machine Learning"),
                    ("CV", "Computer Vision"),
                    ("NLP", "Natural Language Processing"),
                    ("CY", "Cybersecurity"),
                    ("UI", "UI/UX Design"),
                    ("PM", "Product Management"),
                    ("CL", "Cloud Computing"),
                    ("RB", "Robotics"),
                    ("IOT", "Internet of Things"),
                    ("BD", "Big Data"),
                    ("BC", "Blockchain"),
                    ("MB", "Mobile Development"),
                    ("QA", "Quality Assurance"),
                    ("SE", "Software Engineering"),
                    ("DA", "Data Analysis"),
                    ("DB", "Database Administration"),
                    ("NW", "Network Engineering"),
                    ("MK", "Marketing"),
                    ("DM", "Digital Marketing"),
                    ("SM", "Social Media Management"),
                    ("CM", "Content Marketing"),
                    ("SA", "Sales"),
                    ("PR", "Public Relations"),
                    ("AD", "Advertising"),
                    ("BR", "Brand Management"),
                    ("PMK", "Product Marketing"),
                    ("AM", "Agri Marketing"),
                    ("HR", "Human Resources"),
                    ("FN", "Finance"),
                    ("AC", "Accounting"),
                    ("BK", "Banking"),
                    ("IN", "Investment Banking"),
                    ("RE", "Real Estate"),
                    ("LG", "Legal"),
                    ("ED", "Education"),
                    ("TR", "Teaching & Training"),
                    ("RD", "Research & Development"),
                    ("CT", "Catering"),
                    ("HS", "Hospitality"),
                    ("EV", "Event Management"),
                    ("FT", "Fashion & Textile"),
                    ("AR", "Architecture"),
                    ("ID", "Interior Design"),
                    ("MD", "Medical"),
                    ("PH", "Pharmacy"),
                    ("SP", "Sports & Fitness"),
                    ("EN", "Entrepreneurship"),
                    ("AGR", "Agriculture"),
                    ("OT", "Others"),
                ],
                max_length=50,
            ),
        ),
    ]
