# Generated by Django 5.1.5 on 2025-04-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0014_alter_portfolio_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="facebook",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="profile",
            name="github",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="profile",
            name="linkedin",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="profile",
            name="twitter",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="profile",
            name="whatapp",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="category",
            field=models.CharField(
                choices=[
                    ("WebDev", "WebDev"),
                    ("DataScience", "DataScience"),
                    ("AI", "AI"),
                    ("MachineLearning", "MachineLearning"),
                    ("ComputerVision", "ComputerVision"),
                    ("NLP", "NLP"),
                    ("Cybersecurity", "Cybersecurity"),
                    ("UIUX", "UIUX"),
                    ("ProductManagement", "ProductManagement"),
                    ("CloudComputing", "CloudComputing"),
                    ("Robotics", "Robotics"),
                    ("IoT", "IoT"),
                    ("BigData", "BigData"),
                    ("Blockchain", "Blockchain"),
                    ("MobileDev", "MobileDev"),
                    ("QA", "QA"),
                    ("SoftwareEng", "SoftwareEng"),
                    ("DataAnalysis", "DataAnalysis"),
                    ("DatabaseAdmin", "DatabaseAdmin"),
                    ("NetworkEng", "NetworkEng"),
                    ("Marketing", "Marketing"),
                    ("DigitalMarketing", "DigitalMarketing"),
                    ("SocialMedia", "SocialMedia"),
                    ("ContentMarketing", "ContentMarketing"),
                    ("Sales", "Sales"),
                    ("PublicRelations", "PublicRelations"),
                    ("Advertising", "Advertising"),
                    ("BrandManagement", "BrandManagement"),
                    ("ProductMarketing", "ProductMarketing"),
                    ("AgriMarketing", "AgriMarketing"),
                    ("HumanResources", "HumanResources"),
                    ("Finance", "Finance"),
                    ("Accounting", "Accounting"),
                    ("Banking", "Banking"),
                    ("InvestmentBanking", "InvestmentBanking"),
                    ("RealEstate", "RealEstate"),
                    ("Legal", "Legal"),
                    ("Education", "Education"),
                    ("Teaching", "Teaching"),
                    ("Research", "Research"),
                    ("Catering", "Catering"),
                    ("Hospitality", "Hospitality"),
                    ("EventManagement", "EventManagement"),
                    ("Fashion", "Fashion"),
                    ("Architecture", "Architecture"),
                    ("InteriorDesign", "InteriorDesign"),
                    ("Medical", "Medical"),
                    ("Pharmacy", "Pharmacy"),
                    ("Sports", "Sports"),
                    ("Entrepreneurship", "Entrepreneurship"),
                    ("Agriculture", "Agriculture"),
                    ("Others", "Others"),
                ],
                max_length=50,
            ),
        ),
    ]
